import fs from 'node:fs';
const html = fs.readFileSync('www.niwin.info/index.html', 'utf-8');
import { JSDOM } from 'jsdom';
const dom = new JSDOM(html);
console.log("== TITLES ==");
console.log(dom.window.document.title);
console.log("== LINKS ==");
dom.window.document.querySelectorAll('link').forEach(l => console.log(l.href));
console.log("== SCRIPTS ==");
dom.window.document.querySelectorAll('script').forEach(s => console.log(s.src || s.innerHTML.substring(0, 50)));
